---

- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
    state: latest
  

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created3
  become: yes
  become_user: postgres
  postgresql_db: name={{ db_name }}
                 state=present

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user: name={{ db_user }}
                   role_attr_flags=SUPERUSER,CREATEDB
                   state=present

